In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
from utils import annotate_dataset
import json

In [2]:
annotations = annotate_dataset('mvtec_anomaly_detection_data', debug=True)
with open('annotations.json', 'w') as f:
    json.dump(annotations, f)

Found 15 detection objects.
Detection objects: ['bottle', 'cable', 'capsule', 'carpet', 'grid', 'hazelnut', 'leather', 'metal_nut', 'pill', 'screw', 'tile', 'toothbrush', 'transistor', 'wood', 'zipper']
Annotating: bottle (1/15)
Found 3 classes in mvtec_anomaly_detection_data\bottle\ground_truth
Classes: ['broken_large', 'broken_small', 'contamination']
[[687 284]]
[687 284]
[[723 388]]
[723 388]
[[425 148]]
[425 148]
[[440  44]]
[440  44]
[[418 175]]
[418 175]
[[566 186]]
[566 186]
[[420  60]]
[420  60]
[[264 234]]
[264 234]
[[687 322]]
[687 322]
[[499 128]]
[499 128]
[[440 148]]
[440 148]
[[739 429]]
[739 429]
[[486 156]]
[486 156]
[[454 130]]
[454 130]
[[184 354]]
[184 354]
[[613 208]]
[613 208]
[[587 153]]
[587 153]
[[434 123]]
[434 123]
[[436 172]]
[436 172]
[[508 158]]
[508 158]
[[207 526]]
[207 526]
[[271 580]]
[271 580]
[[571 193]]
[571 193]
[[220 428]]
[220 428]
[[183 503]]
[183 503]
[[314 593]]
[314 593]
[[511 150]]
[511 150]
[[688 302]]
[688 302]
[[622 556]]
[622 556]
[[320 

KeyboardInterrupt: 